// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6wcI4qTF334k7XOKxpNphFxjQohjaGQc',
    appId: '1:483827152768:web:358d15df1b897bd8ec7365',
    messagingSenderId: '483827152768',
    projectId: 'wordspark-c4bcd',
    authDomain: 'wordspark-c4bcd.firebaseapp.com',
    storageBucket: 'wordspark-c4bcd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbP0c9s8xWOxYuQDctCfer_y-ih3c5Uv0',
    appId: '1:483827152768:android:801fb842881e7e34ec7365',
    messagingSenderId: '483827152768',
    projectId: 'wordspark-c4bcd',
    storageBucket: 'wordspark-c4bcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2iwBvmCbUSA_W9n-v68Jj7Gx4cUA1Ug8',
    appId: '1:483827152768:ios:6f7348bd6de89f17ec7365',
    messagingSenderId: '483827152768',
    projectId: 'wordspark-c4bcd',
    storageBucket: 'wordspark-c4bcd.firebasestorage.app',
    iosBundleId: 'com.example.wordspark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2iwBvmCbUSA_W9n-v68Jj7Gx4cUA1Ug8',
    appId: '1:483827152768:ios:6f7348bd6de89f17ec7365',
    messagingSenderId: '483827152768',
    projectId: 'wordspark-c4bcd',
    storageBucket: 'wordspark-c4bcd.firebasestorage.app',
    iosBundleId: 'com.example.wordspark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6wcI4qTF334k7XOKxpNphFxjQohjaGQc',
    appId: '1:483827152768:web:b2bdefd871d08d07ec7365',
    messagingSenderId: '483827152768',
    projectId: 'wordspark-c4bcd',
    authDomain: 'wordspark-c4bcd.firebaseapp.com',
    storageBucket: 'wordspark-c4bcd.firebasestorage.app',
  );
}
